---
kind: pipeline
name: amd64
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.5.0
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/klipper-helm"
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
    build_args:
    - ARCH=amd64
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm64
type: docker

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rancher/dapper:v0.5.0
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/klipper-helm"
    tag: "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
    build_args:
    - ARCH=arm64
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm
type: docker

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: rancher/dapper:v0.5.0
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/klipper-helm"
    tag: "${DRONE_TAG}-arm"
    username:
      from_secret: docker_username
    build_args:
    - ARCH=arm
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: s390x
type: docker

platform:
  os: linux
  arch: amd64

node:
  arch: s390x

steps:
- name: build
  image: rancher/dapper:v0.5.7
  failure: ignore
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: docker-publish
  image: plugins/docker
  failure: ignore
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/klipper-helm"
    tag: "${DRONE_TAG}-s390x"
    username:
      from_secret: docker_username
    build_args:
    - ARCH=s390x
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
      - linux/s390x
    target: "rancher/klipper-helm:${DRONE_TAG}"
    template: "rancher/klipper-helm:${DRONE_TAG}-ARCH"
    ignore_missing: true
  when:
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

depends_on:
- amd64
- arm64
- arm
- s390x

...
