#!/bin/bash
set -e -x

tiller --listen=127.0.0.1:44134 --storage=secret &
export HELM_HOST=127.0.0.1:44134

helm init --client-only
if [ -n "$REPO" ]; then
    helm repo add ${NAME%%/*} $REPO
fi
helm repo update


JQ_CMD='"\(.Releases[0].AppVersion) \(.Releases[0].Status)"'
LINE="$(helm ls --all "^$NAME\$" --output json | jq -r "$JQ_CMD")"
INSTALLED_VERSION=$(echo $LINE | awk '{print $1}')
STATUS=$(echo $LINE | awk '{print $2}')

if [ -e /config/values.yaml ]; then
    VALUES="--values /config/values.yaml"
fi

if [ "$1" = "delete" ]; then
    if [ -z "$INSTALLED_VERSION" ]; then
        exit
    fi
    helm "$@"
    exit
fi

if [ -z "$INSTALLED_VERSION" ]; then
    helm "$@" $VALUES
    exit
fi
if [ -z "$VERSION" ] || [ "$INSTALLED_VERSION" = "$VERSION" ]; then
    if [ "$STATUS" = "DEPLOYED" ]; then
        echo Already installed $NAME
        exit
    fi
fi

if [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "DELETED" ]; then
    helm delete --purge $NAME
    echo Deleted
    helm "$@" $VALUES
    exit
fi

# We assume the args are always install --name foo CHART
shift 2
helm upgrade "$@" $VALUES
