name: Cleanup

on:
  workflow_call:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load environment
        uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: .github/development.env

      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v4
        with:
          name: ${{ env.IMAGE }}
          token: ${{ secrets.PAT_CI_BOUNDLESS }}